# Diseño de la encuesta

El diseño de la encuesta está formada por 2 grandes secciones. Uno referido al diseño del cuestionario y la otra al diseño de la selección de los casos. El primero refiere a que se pregunta y el segundo a quienes. En ambos casos en general explicitan pero pocas veces justifican las decisiones tomadas. En otras palabras, la palabra "diseño" le queda grande a ambas secciones. La meta justificación es que se trata de una actividad con fines principalmente pedagógicos más que académicos.

## Diseño del cuestionario

El cuestionario, como muchos cuestionarios que se usan en la práctica profesional, está diseñado con la lógica de módulos. Como veremos más adelante cada módulo tiene una justificable lógica interna pero lo que no tiene este cuestionario es una coherencia interna que explique la relación entre los diferentes módulos.

El diseño de un cuestionario mediante la estrategia de módulos suele ser útil tanto para el encuestado como para el investigador. Al encuestado lo ayuda a ordenarse visualmente especialmente si se trata de un cuestionario largo. Al investigador lo ayuda tanto para el nombre como para el orden de las variables en la base de datos.

El cuestionario cuenta con los siguientes módulos:

1.  Identificación

2.  Demográfico

3.  Composición del hogar

4.  Cuidados

5.  Vivienda

6.  Uso del tiempo

7.  Inseguridad alimentaria

8.  Preferencias sociales

9.  Origen social

10. Trabajo actual

11. Ingresos del hogar

12. Académico UNAJ

13. Expectativas materia cuantitativa

14. Redes sociales entre estudiantes de la materia

## Diseño de la selección de casos

En cuanto al criterio utilizado para la selección de los casos puede afirmar que se trata de una muestra de los estudiantes de la materia "Metodología y Técnicas Cuantitativas" de la carrera de Trabajo Social de la Universidad Nacional Arturo Jauretche. Esto dice algo
